[WIP] Adding setup stuff

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,18 +3,62 @@ set -e
 set -o pipefail
 
 RUBY_VERSION=2.1.6
+CHEF_VERSION=12.9.41
 
 USER=$(whoami)
 : ${HOME:="/Users/$USER"}
 
-echo '----> Install xcode command line tools (click "Install")'
-xcode-select --install
+# Don't run as sudo
+if [[ $EUID -eq 0 ]]; then
+  echo "ERROR: Don't run as sudo"
+  exit 1
+fi
+
+echo '----> Creating ~/.bash_profile'
+tee ~/.bash_profile <<EOF
+if [ -f ~/.bashrc ]; then
+  . ~/.bashrc
+fi
+
+# Customizations can be placed into ~/.bash_profile_includes/ with a .sh extension
+for file in ~/.bash_profile_includes/*.sh; do
+  [[ -r $file ]] && source $file;
+done
+EOF
+chmod 644 ~/.bash_profile
+
+echo '----> Creating ~/.bash_profile_includes/defaults.sh'
+mkdir -p ~/.bash_profile_includes
+tee ~/.bash_profile_includes/defaults.sh <<EOF
+export PATH=$HOME/bin:/usr/local/bin:$PATH
+
+alias ll='ls -lhA'
+alias grep='grep --color=auto'
+alias egrep='egrep --color=auto'
+alias reset_dns='sudo killall -HUP mDNSResponder'
+
+# alias over knife to make it faster
+alias knifef="BUNDLE_GEMFILE=~/workspace/dotfiles/Gemfile bundle exec knife"
+
+function knives() {
+  if [ -z "$2" ]
+  then knifef ssh "$1" "hostname" -x lumoslabs -a hostname | sort
+  else knifef ssh "$1" "$2" -x lumoslabs -a hostname | sort
+  fi
+}
+EOF
+chmod 755 ~/.bash_profile_includes/defaults.sh
+
+echo '----> Installing xcode command line tools (click "Install")'
+xcode-select --install || true
 
 echo '----> Installing Homebrew'
-/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-brew install rcmdnk/file/brew-file
-brew file set_repo --repo lumoslabs/dotfiles
-brew file install
+/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || true
+# brew install rcmdnk/file/brew-file
+# brew file set_repo --repo lumoslabs/dotfiles
+brew tap Homebrew/bundle
+brew bundle
+# brew file install
 
 echo '----> Installing ruby $RUBY_VERSION'
 rbenv install $RUBY_VERSION
@@ -30,10 +74,10 @@ if [ ! -f "$HOME/.ssh/github-key" ]; then
 fi
 
 if [ ! -d ~/workspace/chef-data-bags ]; then
-  echo '----> Clone data-bags repo & install dependencies'
+  echo '----> Cloning data-bags repo & install dependencies'
   git clone git@github.com:lumoslabs/chef-data-bags ~/workspace/chef-data-bags
 else
-  echo '----> Update data-bags repo'
+  echo '----> Updating data-bags repo'
   pushd ~/workspace/chef-data-bags >/dev/null
   git fetch --all
   git merge --ff-only @{u}
@@ -79,7 +123,7 @@ verify_api_cert          false
 versioned_cookbooks      true
 
 knife[:editor]                = 'vim'
-knife[:bootstrap_version]     = "12.5.1"
+knife[:bootstrap_version]     = "$CHEF_VERSION"
 knife[:secret_file]           = "#{chef_dir}/memory.key"
 knife[:aws_access_key_id]     = ENV['AWS_ACCESS_KEY_ID']
 knife[:aws_secret_access_key] = ENV['AWS_SECRET_ACCESS_KEY']
